### ISSUE TITLE
Fail of contracting an isolated singularity II

### ISSUE THREAD

**Issue by HdXu** [homotopy-io/homotopy-rs#117]
I found an operation causing panic in homotopy.io In singular level (pic3.), try to drag the string to the left.

**Screenshots**
<img width="167" alt="Screenshot 2021-07-08 at 16 03 29" src="https://user-images.githubusercontent.com/35509721/124945442-fe6ae580-dfc2-11eb-884e-c994bbff990a.png">
_pic1. 4-cell_
<img width="278" alt="Screenshot 2021-07-08 at 16 05 08" src="https://user-images.githubusercontent.com/35509721/124945680-3a9e4600-dfc3-11eb-856f-370fcf826bcf.png">
_pic2. source 3-cell_
<img width="278" alt="Screenshot 2021-07-08 at 16 07 03" src="https://user-images.githubusercontent.com/35509721/124945991-7df8b480-dfc3-11eb-9180-b2a2cf05a9fb.png">
_pic3. singular 3-cell_
<img width="278" alt="Screenshot 2021-07-08 at 16 05 45" src="https://user-images.githubusercontent.com/35509721/124945764-4ee24300-dfc3-11eb-8d0b-d657853cb053.png">
_pic4. target 3-cell_

**Project Demo**
[bug-isolated singularity2.hom.zip](https://github.com/homotopy-io/homotopy-rs/files/6785604/bug-isolated.singularity2.hom.zip)

**Error report 1:**
`panicked at 'index out of bounds: the len is 0 but the index is 0', homotopy-core/src/factorization.rs:103:47`
`Stack:`
`Error
    at x (https://beta.homotopy.io/235.js:1:9598)
    at console_error_panic_hook::hook::h6aba13f31c7bca6d (https://beta.homotopy.io/4ab508ae2f09a90d11ee.module.wasm:wasm-function[914]:0x1487ec)
    at core::ops::function::Fn::call::h042126be8e13bf49 (https://beta.homotopy.io/4ab508ae2f09a90d11ee.module.wasm:wasm-function[2618]:0x197206)
    at std::panicking::rust_panic_with_hook::hbdbceb5cd158bf19 (https://beta.homotopy.io/4ab508ae2f09a90d11ee.module.wasm:wasm-function[1674]:0x185228)
    at std::panicking::begin_panic_handler::{{closure}}::h9995bb2f0de4bb38 (https://beta.homotopy.io/4ab508ae2f09a90d11ee.module.wasm:wasm-function[1849]:0x18d0de)
    at std::sys_common::backtrace::__rust_end_short_backtrace::hc7608161a467c002 (https://beta.homotopy.io/4ab508ae2f09a90d11ee.module.wasm:wasm-function[2187]:0x194cd2)
    at rust_begin_unwind (https://beta.homotopy.io/4ab508ae2f09a90d11ee.module.wasm:wasm-function[2131]:0x194141)
    at core::panicking::panic_fmt::h3ab5417155b7ba3b (https://beta.homotopy.io/4ab508ae2f09a90d11ee.module.wasm:wasm-function[2188]:0x194d08)
    at core::panicking::panic_bounds_check::hb15177e067923215 (https://beta.homotopy.io/4ab508ae2f09a90d11ee.module.wasm:wasm-function[1943]:0x190082)
   at homotopy_core::factorization::factorize::h65dd9a73753e00b8 (https://beta.homotopy.io/4ab508ae2f09a90d11ee.module.wasm:wasm-function[194]:0x819f6)
`

`B @ 235.js:1
console_error_panic_hook::hook::h6aba13f31c7bca6d @ 4ab508ae2f09a90d11ee.module.wasm:0x1488ce
core::ops::function::Fn::call::h042126be8e13bf49 @ 4ab508ae2f09a90d11ee.module.wasm:0x197206
std::panicking::rust_panic_with_hook::hbdbceb5cd158bf19 @ 4ab508ae2f09a90d11ee.module.wasm:0x185228
std::panicking::begin_panic_handler::{{closure}}::h9995bb2f0de4bb38 @ 4ab508ae2f09a90d11ee.module.wasm:0x18d0de
std::sys_common::backtrace::__rust_end_short_backtrace::hc7608161a467c002 @ 4ab508ae2f09a90d11ee.module.wasm:0x194cd2
rust_begin_unwind @ 4ab508ae2f09a90d11ee.module.wasm:0x194141
core::panicking::panic_fmt::h3ab5417155b7ba3b @ 4ab508ae2f09a90d11ee.module.wasm:0x194d08
core::panicking::panic_bounds_check::hb15177e067923215 @ 4ab508ae2f09a90d11ee.module.wasm:0x190082
homotopy_core::factorization::factorize::h65dd9a73753e00b8 @ 4ab508ae2f09a90d11ee.module.wasm:0x819f6
homotopy_core::expansion::expand_in_path::hc3b2c1c917ffc45b @ 4ab508ae2f09a90d11ee.module.wasm:0x1e0f4
homotopy_core::expansion::<impl homotopy_core::diagram::DiagramN>::expand::{{closure}}::h83b7ca05fea9d63d @ 4ab508ae2f09a90d11ee.module.wasm:0xf3772
homotopy_core::attach::attach_worker::hb60fb8c4ee4eff1e @ 4ab508ae2f09a90d11ee.module.wasm:0xb7296
homotopy_web::model::proof::ProofState::update::he9d3f357ecde8691 @ 4ab508ae2f09a90d11ee.module.wasm:0xa461
homotopy_web::model::State::update::hc534deb828780a5f @ 4ab508ae2f09a90d11ee.module.wasm:0x2c671
<homotopy_web::app::App as yew::html::component::Component>::update::h2c8328a44d0ecb9a @ 4ab508ae2f09a90d11ee.module.wasm:0x11a9c2
<yew::html::component::lifecycle::ComponentRunnable<COMP> as yew::scheduler::Runnable>::run::h39ba2e481bf20f77 @ 4ab508ae2f09a90d11ee.module.wasm:0x9335b
yew::scheduler::Scheduler::start::h49a9c034775ead2e @ 4ab508ae2f09a90d11ee.module.wasm:0x10c4f1
yew::html::component::scope::Scope<COMP>::process::ha0ec65fa04fc1879 @ 4ab508ae2f09a90d11ee.module.wasm:0x18caec
<homotopy_web::app::diagram2d::Diagram2D as yew::html::component::Component>::view::{{closure}}::hf972da02dd28c302 @ 4ab508ae2f09a90d11ee.module.wasm:0x18e500
<yew::html::listener::events::oncanplaythrough::Wrapper as yew::virtual_dom::Listener>::attach::{{closure}}::h0a48eb8113e6d213 @ 4ab508ae2f09a90d11ee.module.wasm:0x186eac
<dyn core::ops::function::FnMut<(&A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h1864696aafdd1a77 @ 4ab508ae2f09a90d11ee.module.wasm:0x1940bc
H @ 235.js:1
r @ 235.js:1`
`4ab508ae2f09a90d11ee.module.wasm:0x197456 Uncaught RuntimeError: unreachable
    at __rust_start_panic (4ab508ae2f09a90d11ee.module.wasm:0x197456)
    at rust_panic (4ab508ae2f09a90d11ee.module.wasm:0x19540f)
    at std::panicking::rust_panic_with_hook::hbdbceb5cd158bf19 (4ab508ae2f09a90d11ee.module.wasm:0x18524c)
    at std::panicking::begin_panic_handler::{{closure}}::h9995bb2f0de4bb38 (4ab508ae2f09a90d11ee.module.wasm:0x18d0de)
    at std::sys_common::backtrace::__rust_end_short_backtrace::hc7608161a467c002 (4ab508ae2f09a90d11ee.module.wasm:0x194cd2)
    at rust_begin_unwind (4ab508ae2f09a90d11ee.module.wasm:0x194141)
    at core::panicking::panic_fmt::h3ab5417155b7ba3b (4ab508ae2f09a90d11ee.module.wasm:0x194d08)
    at core::panicking::panic_bounds_check::hb15177e067923215 (4ab508ae2f09a90d11ee.module.wasm:0x190082)
    at homotopy_core::factorization::factorize::h65dd9a73753e00b8 (4ab508ae2f09a90d11ee.module.wasm:0x819f6)
    at homotopy_core::expansion::expand_in_path::hc3b2c1c917ffc45b (4ab508ae2f09a90d11ee.module.wasm:0x1e0f4)
__rust_start_panic @ 4ab508ae2f09a90d11ee.module.wasm:0x197456
rust_panic @ 4ab508ae2f09a90d11ee.module.wasm:0x19540f
std::panicking::rust_panic_with_hook::hbdbceb5cd158bf19 @ 4ab508ae2f09a90d11ee.module.wasm:0x18524c
std::panicking::begin_panic_handler::{{closure}}::h9995bb2f0de4bb38 @ 4ab508ae2f09a90d11ee.module.wasm:0x18d0de
std::sys_common::backtrace::__rust_end_short_backtrace::hc7608161a467c002 @ 4ab508ae2f09a90d11ee.module.wasm:0x194cd2
rust_begin_unwind @ 4ab508ae2f09a90d11ee.module.wasm:0x194141
core::panicking::panic_fmt::h3ab5417155b7ba3b @ 4ab508ae2f09a90d11ee.module.wasm:0x194d08
core::panicking::panic_bounds_check::hb15177e067923215 @ 4ab508ae2f09a90d11ee.module.wasm:0x190082
homotopy_core::factorization::factorize::h65dd9a73753e00b8 @ 4ab508ae2f09a90d11ee.module.wasm:0x819f6
homotopy_core::expansion::expand_in_path::hc3b2c1c917ffc45b @ 4ab508ae2f09a90d11ee.module.wasm:0x1e0f4
homotopy_core::expansion::<impl homotopy_core::diagram::DiagramN>::expand::{{closure}}::h83b7ca05fea9d63d @ 4ab508ae2f09a90d11ee.module.wasm:0xf3772
homotopy_core::attach::attach_worker::hb60fb8c4ee4eff1e @ 4ab508ae2f09a90d11ee.module.wasm:0xb7296
homotopy_web::model::proof::ProofState::update::he9d3f357ecde8691 @ 4ab508ae2f09a90d11ee.module.wasm:0xa461
homotopy_web::model::State::update::hc534deb828780a5f @ 4ab508ae2f09a90d11ee.module.wasm:0x2c671
<homotopy_web::app::App as yew::html::component::Component>::update::h2c8328a44d0ecb9a @ 4ab508ae2f09a90d11ee.module.wasm:0x11a9c2
<yew::html::component::lifecycle::ComponentRunnable<COMP> as yew::scheduler::Runnable>::run::h39ba2e481bf20f77 @ 4ab508ae2f09a90d11ee.module.wasm:0x9335b
yew::scheduler::Scheduler::start::h49a9c034775ead2e @ 4ab508ae2f09a90d11ee.module.wasm:0x10c4f1
yew::html::component::scope::Scope<COMP>::process::ha0ec65fa04fc1879 @ 4ab508ae2f09a90d11ee.module.wasm:0x18caec
<homotopy_web::app::diagram2d::Diagram2D as yew::html::component::Component>::view::{{closure}}::hf972da02dd28c302 @ 4ab508ae2f09a90d11ee.module.wasm:0x18e500
<yew::html::listener::events::oncanplaythrough::Wrapper as yew::virtual_dom::Listener>::attach::{{closure}}::h0a48eb8113e6d213 @ 4ab508ae2f09a90d11ee.module.wasm:0x186eac
<dyn core::ops::function::FnMut<(&A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h1864696aafdd1a77 @ 4ab508ae2f09a90d11ee.module.wasm:0x1940bc
H @ 235.js:1
r @ 235.js:1`

**Error report 2:**
`panicked at 'index out of bounds: the len is 0 but the index is 0', homotopy-core/src/factorization.rs:103:47 `
`Stack:`
`Error
    at x (https://beta.homotopy.io/235.js:1:9598)
    at console_error_panic_hook::hook::h6aba13f31c7bca6d (https://beta.homotopy.io/4ab508ae2f09a90d11ee.module.wasm:wasm-function[914]:0x1487ec)
    at core::ops::function::Fn::call::h042126be8e13bf49 (https://beta.homotopy.io/4ab508ae2f09a90d11ee.module.wasm:wasm-function[2618]:0x197206)
    at std::panicking::rust_panic_with_hook::hbdbceb5cd158bf19 (https://beta.homotopy.io/4ab508ae2f09a90d11ee.module.wasm:wasm-function[1674]:0x185228)
    at std::panicking::begin_panic_handler::{{closure}}::h9995bb2f0de4bb38 (https://beta.homotopy.io/4ab508ae2f09a90d11ee.module.wasm:wasm-function[1849]:0x18d0de)
    at std::sys_common::backtrace::__rust_end_short_backtrace::hc7608161a467c002 (https://beta.homotopy.io/4ab508ae2f09a90d11ee.module.wasm:wasm-function[2187]:0x194cd2)
    at rust_begin_unwind (https://beta.homotopy.io/4ab508ae2f09a90d11ee.module.wasm:wasm-function[2131]:0x194141)
    at core::panicking::panic_fmt::h3ab5417155b7ba3b (https://beta.homotopy.io/4ab508ae2f09a90d11ee.module.wasm:wasm-function[2188]:0x194d08)
    at core::panicking::panic_bounds_check::hb15177e067923215 (https://beta.homotopy.io/4ab508ae2f09a90d11ee.module.wasm:wasm-function[1943]:0x190082)
    at homotopy_core::factorization::factorize::h65dd9a73753e00b8 (https://beta.homotopy.io/4ab508ae2f09a90d11ee.module.wasm:wasm-function[194]:0x819f6)
`

`B @ 235.js:1
console_error_panic_hook::hook::h6aba13f31c7bca6d @ 4ab508ae2f09a90d11ee.module.wasm:0x1488ce
core::ops::function::Fn::call::h042126be8e13bf49 @ 4ab508ae2f09a90d11ee.module.wasm:0x197206
std::panicking::rust_panic_with_hook::hbdbceb5cd158bf19 @ 4ab508ae2f09a90d11ee.module.wasm:0x185228
std::panicking::begin_panic_handler::{{closure}}::h9995bb2f0de4bb38 @ 4ab508ae2f09a90d11ee.module.wasm:0x18d0de
std::sys_common::backtrace::__rust_end_short_backtrace::hc7608161a467c002 @ 4ab508ae2f09a90d11ee.module.wasm:0x194cd2
rust_begin_unwind @ 4ab508ae2f09a90d11ee.module.wasm:0x194141
core::panicking::panic_fmt::h3ab5417155b7ba3b @ 4ab508ae2f09a90d11ee.module.wasm:0x194d08
core::panicking::panic_bounds_check::hb15177e067923215 @ 4ab508ae2f09a90d11ee.module.wasm:0x190082
homotopy_core::factorization::factorize::h65dd9a73753e00b8 @ 4ab508ae2f09a90d11ee.module.wasm:0x819f6
homotopy_core::expansion::expand_in_path::hc3b2c1c917ffc45b @ 4ab508ae2f09a90d11ee.module.wasm:0x1e0f4
homotopy_core::expansion::<impl homotopy_core::diagram::DiagramN>::expand::{{closure}}::h83b7ca05fea9d63d @ 4ab508ae2f09a90d11ee.module.wasm:0xf3772
homotopy_core::attach::attach_worker::hb60fb8c4ee4eff1e @ 4ab508ae2f09a90d11ee.module.wasm:0xb7296
homotopy_web::model::proof::ProofState::update::he9d3f357ecde8691 @ 4ab508ae2f09a90d11ee.module.wasm:0xa461
homotopy_web::model::State::update::hc534deb828780a5f @ 4ab508ae2f09a90d11ee.module.wasm:0x2c671
<homotopy_web::app::App as yew::html::component::Component>::update::h2c8328a44d0ecb9a @ 4ab508ae2f09a90d11ee.module.wasm:0x11a9c2
<yew::html::component::lifecycle::ComponentRunnable<COMP> as yew::scheduler::Runnable>::run::h39ba2e481bf20f77 @ 4ab508ae2f09a90d11ee.module.wasm:0x9335b
yew::scheduler::Scheduler::start::h49a9c034775ead2e @ 4ab508ae2f09a90d11ee.module.wasm:0x10c4f1
yew::html::component::scope::Scope<COMP>::process::ha0ec65fa04fc1879 @ 4ab508ae2f09a90d11ee.module.wasm:0x18caec
<homotopy_web::app::diagram2d::Diagram2D as yew::html::component::Component>::view::{{closure}}::hf972da02dd28c302 @ 4ab508ae2f09a90d11ee.module.wasm:0x18e500
<yew::html::listener::events::oncanplaythrough::Wrapper as yew::virtual_dom::Listener>::attach::{{closure}}::h0a48eb8113e6d213 @ 4ab508ae2f09a90d11ee.module.wasm:0x186eac
<dyn core::ops::function::FnMut<(&A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h1864696aafdd1a77 @ 4ab508ae2f09a90d11ee.module.wasm:0x1940bc
H @ 235.js:1
r @ 235.js:1`
`4ab508ae2f09a90d11ee.module.wasm:0x197456 Uncaught RuntimeError: unreachable
    at __rust_start_panic (4ab508ae2f09a90d11ee.module.wasm:0x197456)
    at rust_panic (4ab508ae2f09a90d11ee.module.wasm:0x19540f)
    at std::panicking::rust_panic_with_hook::hbdbceb5cd158bf19 (4ab508ae2f09a90d11ee.module.wasm:0x18524c)
    at std::panicking::begin_panic_handler::{{closure}}::h9995bb2f0de4bb38 (4ab508ae2f09a90d11ee.module.wasm:0x18d0de)
    at std::sys_common::backtrace::__rust_end_short_backtrace::hc7608161a467c002 (4ab508ae2f09a90d11ee.module.wasm:0x194cd2)
    at rust_begin_unwind (4ab508ae2f09a90d11ee.module.wasm:0x194141)
    at core::panicking::panic_fmt::h3ab5417155b7ba3b (4ab508ae2f09a90d11ee.module.wasm:0x194d08)
    at core::panicking::panic_bounds_check::hb15177e067923215 (4ab508ae2f09a90d11ee.module.wasm:0x190082)
    at homotopy_core::factorization::factorize::h65dd9a73753e00b8 (4ab508ae2f09a90d11ee.module.wasm:0x819f6)
    at homotopy_core::expansion::expand_in_path::hc3b2c1c917ffc45b (4ab508ae2f09a90d11ee.module.wasm:0x1e0f4)
__rust_start_panic @ 4ab508ae2f09a90d11ee.module.wasm:0x197456
rust_panic @ 4ab508ae2f09a90d11ee.module.wasm:0x19540f
std::panicking::rust_panic_with_hook::hbdbceb5cd158bf19 @ 4ab508ae2f09a90d11ee.module.wasm:0x18524c
std::panicking::begin_panic_handler::{{closure}}::h9995bb2f0de4bb38 @ 4ab508ae2f09a90d11ee.module.wasm:0x18d0de
std::sys_common::backtrace::__rust_end_short_backtrace::hc7608161a467c002 @ 4ab508ae2f09a90d11ee.module.wasm:0x194cd2
rust_begin_unwind @ 4ab508ae2f09a90d11ee.module.wasm:0x194141
core::panicking::panic_fmt::h3ab5417155b7ba3b @ 4ab508ae2f09a90d11ee.module.wasm:0x194d08
core::panicking::panic_bounds_check::hb15177e067923215 @ 4ab508ae2f09a90d11ee.module.wasm:0x190082
homotopy_core::factorization::factorize::h65dd9a73753e00b8 @ 4ab508ae2f09a90d11ee.module.wasm:0x819f6
homotopy_core::expansion::expand_in_path::hc3b2c1c917ffc45b @ 4ab508ae2f09a90d11ee.module.wasm:0x1e0f4
homotopy_core::expansion::<impl homotopy_core::diagram::DiagramN>::expand::{{closure}}::h83b7ca05fea9d63d @ 4ab508ae2f09a90d11ee.module.wasm:0xf3772
homotopy_core::attach::attach_worker::hb60fb8c4ee4eff1e @ 4ab508ae2f09a90d11ee.module.wasm:0xb7296
homotopy_web::model::proof::ProofState::update::he9d3f357ecde8691 @ 4ab508ae2f09a90d11ee.module.wasm:0xa461
homotopy_web::model::State::update::hc534deb828780a5f @ 4ab508ae2f09a90d11ee.module.wasm:0x2c671
<homotopy_web::app::App as yew::html::component::Component>::update::h2c8328a44d0ecb9a @ 4ab508ae2f09a90d11ee.module.wasm:0x11a9c2
<yew::html::component::lifecycle::ComponentRunnable<COMP> as yew::scheduler::Runnable>::run::h39ba2e481bf20f77 @ 4ab508ae2f09a90d11ee.module.wasm:0x9335b
yew::scheduler::Scheduler::start::h49a9c034775ead2e @ 4ab508ae2f09a90d11ee.module.wasm:0x10c4f1
yew::html::component::scope::Scope<COMP>::process::ha0ec65fa04fc1879 @ 4ab508ae2f09a90d11ee.module.wasm:0x18caec
<homotopy_web::app::diagram2d::Diagram2D as yew::html::component::Component>::view::{{closure}}::hf972da02dd28c302 @ 4ab508ae2f09a90d11ee.module.wasm:0x18e500
<yew::html::listener::events::oncanplaythrough::Wrapper as yew::virtual_dom::Listener>::attach::{{closure}}::h0a48eb8113e6d213 @ 4ab508ae2f09a90d11ee.module.wasm:0x186eac
<dyn core::ops::function::FnMut<(&A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h1864696aafdd1a77 @ 4ab508ae2f09a90d11ee.module.wasm:0x1940bc
H @ 235.js:1
r @ 235.js:1`

**Comment by jamievicary** [comment]
Great Hao keep them coming!

**Comment by jamievicary** [comment]
Looks like a bug in the factorization code. I think factorization should actually fail here, but it should of course fail gracefully with a toast, not panic. So it might not be a bug per se, just a failure case being incorrectly handled.

**Comment by jamievicary** [comment]
Nick did you write the factorization code? Maybe you could take a look. This stuff is high-priority at the moment (like everything else :)) because it blocks Hao from being able to make progress.

**Comment by NickHu** [comment]
This happens because the factorisation tries to find a singular map function with nonempty domain but empty codomain (the target 3-diagram is an identity on a 2-diagram, so therefore has no singular levels.), which doesn't exist - so yes, I believe the correct thing to do is to fail here.
