### ISSUE TITLE
Another Crash Log

### ISSUE THREAD

**Issue by wilfofford** [homotopy-io/homotopy-rs#1321]
[homotopy_io_state.zip](https://github.com/homotopy-io/homotopy-rs/files/14157711/homotopy_io_state.zip)

**Comment by regular-citizen** [comment]
The action log contains unsuccessful actions, minor edits to the CLI/web code are needed to rerun it.
This is the result of rerunning the code
```
Performing final action: Homotopy(Expand(Expand { point: [Singular(2), Singular(0)], direction: Forward, location: [Interior(Singular(3))] }))
thread 'main' panicked at homotopy-core/src/expansion.rs:511:18:
index out of bounds: the len is 0 but the index is 0
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: core::panicking::panic_bounds_check
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:162:5
   3: homotopy_core::expansion::expand_propagate
   4: homotopy_core::expansion::expand_in_path
   5: homotopy_core::expansion::<impl homotopy_core::diagram::DiagramN>::expand::{{closure}}
   6: homotopy_core::attach::attach_worker
   7: homotopy_model::proof::ProofState::homotopy_expand
   8: homotopy_model::proof::ProofState::update
   9: homotopy_cli::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
