### ISSUE TITLE
Panic in cubicalisation

### ISSUE THREAD

**Issue by doctorn** [homotopy-io/homotopy-rs#179]
Trying to cubicalise a pentagon causes the following panic:

[pentagon.hom.zip](https://github.com/homotopy-io/homotopy-rs/files/7204761/pentagon.hom.zip)

```
panicked at 'Failed to parallelise', homotopy-core/src/cubicalisation.rs:186:9

Stack:

init/imports.wbg.__wbg_new_59cb74e423758ede@http://0.0.0.0:8080/index-c94d712d028ffb4f.js:357:19
console_error_panic_hook::hook::h09924bd3c257d367@http://0.0.0.0:8080/index-c94d712d028ffb4f_bg.wasm:wasm-function[1118]:0x163493
core::ops::function::Fn::call::hfd75bbe335cd6f44@http://0.0.0.0:8080/index-c94d712d028ffb4f_bg.wasm:wasm-function[3392]:0x1d22bd
std::panicking::rust_panic_with_hook::h2d9079427a2d996a@http://0.0.0.0:8080/index-c94d712d028ffb4f_bg.wasm:wasm-function[2119]:0x1b8ee8
std::panicking::begin_panic::{{closure}}::hf514f05e1bfbeaee@http://0.0.0.0:8080/index-c94d712d028ffb4f_bg.wasm:wasm-function[2879]:0x1cfb17
std::sys_common::backtrace::__rust_end_short_backtrace::h19930395c9041e74@http://0.0.0.0:8080/index-c94d712d028ffb4f_bg.wasm:wasm-function[2835]:0x1cf35f
std::panicking::begin_panic::h00ca6b64e1ec852d@http://0.0.0.0:8080/index-c94d712d028ffb4f_bg.wasm:wasm-function[2878]:0x1cfaea
homotopy_core::cubicalisation::<impl homotopy_core::diagram::Diagram>::cubicalise::h56613ddc0c7d7e65@http://0.0.0.0:8080/index-c94d712d028ffb4f_bg.wasm:wasm-function[581]:0x107241
homotopy_graphics::clay::geom::Mesh::build::h14608dc9979f1376@http://0.0.0.0:8080/index-c94d712d028ffb4f_bg.wasm:wasm-function[180]:0x1bc49
homotopy_web::app::diagram_gl::Scene::buffer_meshes::hd402852364b78b0f@http://0.0.0.0:8080/index-c94d712d028ffb4f_bg.wasm:wasm-function[312]:0xa67c9
<homotopy_web::app::diagram_gl::GlDiagram as yew::html::component::Component>::rendered::hcdfc63019a552df5@http://0.0.0.0:8080/index-c94d712d028ffb4f_bg.wasm:wasm-function[210]:0x498b3
<yew::html::component::lifecycle::ComponentRunnable<COMP> as yew::scheduler::Runnable>::run::h8b79468077ca0d84@http://0.0.0.0:8080/index-c94d712d028ffb4f_bg.wasm:wasm-function[218]:0x53972
std::thread::local::LocalKey<T>::with::hd525b09ea8d8ae50@http://0.0.0.0:8080/index-c94d712d028ffb4f_bg.wasm:wasm-function[2096]:0x1b79c3
yew::scheduler::start::h18d6764a89bf3bd6@http://0.0.0.0:8080/index-c94d712d028ffb4f_bg.wasm:wasm-function[3391]:0x1d22b5
yew::html::component::scope::Scope<COMP>::callback::{{closure}}::hcd278a76b8683cfd@http://0.0.0.0:8080/index-c94d712d028ffb4f_bg.wasm:wasm-function[2281]:0x1c12f5
yew::callback::Callback<IN>::emit::h70345360fe2e79c8@http://0.0.0.0:8080/index-c94d712d028ffb4f_bg.wasm:wasm-function[2072]:0x1b634e
yew::callback::Callback<IN>::reform::{{closure}}::h20298e2379d9f776@http://0.0.0.0:8080/index-c94d712d028ffb4f_bg.wasm:wasm-function[2244]:0x1bf7f3
yew::callback::Callback<IN>::emit::h4838c58e887ef3e4@http://0.0.0.0:8080/index-c94d712d028ffb4f_bg.wasm:wasm-function[1308]:0x1798c5
yew::callback::Callback<IN>::reform::{{closure}}::ha5c4c408318b4530@http://0.0.0.0:8080/index-c94d712d028ffb4f_bg.wasm:wasm-function[2864]:0x1cf885
<homotopy_web::app::workspace::path_control::path_control as yew::functional::FunctionProvider>::run::{{closure}}::{{closure}}::h54d14cbc20db2857@http://0.0.0.0:8080/index-c94d712d028ffb4f_bg.wasm:wasm-function[682]:0x11da71
<yew::html::listener::events::ontransitionend::Wrapper as yew::virtual_dom::Listener>::attach::{{closure}}::hb595a3adf2aa9e89@http://0.0.0.0:8080/index-c94d712d028ffb4f_bg.wasm:wasm-function[2220]:0x1be48b
<dyn core::ops::function::FnMut<(&A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hb9873ce24669ce63@http://0.0.0.0:8080/index-c94d712d028ffb4f_bg.wasm:wasm-function[2776]:0x1ce6ef
__wbg_adapter_37@http://0.0.0.0:8080/index-c94d712d028ffb4f.js:267:14
real@http://0.0.0.0:8080/index-c94d712d028ffb4f.js:199:20
```

**Comment by calintat** [comment]
Oh no, this is bad. This means it failed to find a combination of monotone
maps that commutes. I thought/hoped this wouldn’t be possible.

Thanks for finding this Nathan!

**Comment by doctorn** [comment]
```
panicked at 'Failed to parallelise', homotopy-core/src/cubicalisation.rs:186:9

Stack:

init/imports.wbg.__wbg_new_59cb74e423758ede@http://0.0.0.0:8080/index-96b4a740ab8d33fc.js:357:19
console_error_panic_hook::hook::h09924bd3c257d367@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[1135]:0x16af68
core::ops::function::Fn::call::hfd75bbe335cd6f44@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[3426]:0x1dab94
std::panicking::rust_panic_with_hook::h2d9079427a2d996a@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[2143]:0x1c1496
std::panicking::begin_panic::{{closure}}::hf514f05e1bfbeaee@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[2911]:0x1d83c0
std::sys_common::backtrace::__rust_end_short_backtrace::h19930395c9041e74@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[2865]:0x1d7baf
std::panicking::begin_panic::h00ca6b64e1ec852d@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[2910]:0x1d8393
homotopy_core::cubicalisation::<impl homotopy_core::diagram::Diagram>::cubicalise::h56613ddc0c7d7e65@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[590]:0x10d50f
homotopy_graphics::clay::geom::Mesh::build::h14608dc9979f1376@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[181]:0x1dc84
homotopy_web::app::diagram_gl::Scene::buffer_meshes::hd402852364b78b0f@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[227]:0x5fa89
<homotopy_web::app::diagram_gl::GlDiagram as yew::html::component::Component>::rendered::hcdfc63019a552df5@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[211]:0x4b66b
<yew::html::component::lifecycle::ComponentRunnable<COMP> as yew::scheduler::Runnable>::run::h8b79468077ca0d84@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[218]:0x54371
std::thread::local::LocalKey<T>::with::hd525b09ea8d8ae50@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[2120]:0x1bff71
yew::scheduler::start::h18d6764a89bf3bd6@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[3425]:0x1dab8c
yew::html::component::scope::Scope<COMP>::callback::{{closure}}::hcd278a76b8683cfd@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[2305]:0x1c98a3
yew::callback::Callback<IN>::emit::h70345360fe2e79c8@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[2096]:0x1be8fc
yew::callback::Callback<IN>::reform::{{closure}}::h20298e2379d9f776@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[2268]:0x1c7da1
yew::callback::Callback<IN>::emit::h4838c58e887ef3e4@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[1329]:0x181a41
yew::callback::Callback<IN>::reform::{{closure}}::ha5c4c408318b4530@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[2894]:0x1d80d5
<homotopy_web::app::workspace::path_control::path_control as yew::functional::FunctionProvider>::run::{{closure}}::{{closure}}::h54d14cbc20db2857@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[695]:0x124ab4
<yew::html::listener::events::ontransitionend::Wrapper as yew::virtual_dom::Listener>::attach::{{closure}}::hb595a3adf2aa9e89@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[2244]:0x1c6a39
<dyn core::ops::function::FnMut<(&A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hb9873ce24669ce63@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[2805]:0x1d6f11
__wbg_adapter_37@http://0.0.0.0:8080/index-96b4a740ab8d33fc.js:267:14
real@http://0.0.0.0:8080/index-96b4a740ab8d33fc.js:199:20
EventListener.handleEvent*init/imports.wbg.__wbg_addEventListener_6d9a78a5d277bdaf/<@http://0.0.0.0:8080/index-96b4a740ab8d33fc.js:551:25
handleError@http://0.0.0.0:8080/index-96b4a740ab8d33fc.js:293:18
init/imports.wbg.__wbg_addEventListener_6d9a78a5d277bdaf@http://0.0.0.0:8080/index-96b4a740ab8d33fc.js:550:79
web_sys::features::gen_EventTarget::EventTarget::add_event_listener_with_callback_and_add_event_listener_options::ha29629986626f17e@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[2729]:0x1d5a6e
<yew::html::listener::events::onclick::Wrapper as yew::virtual_dom::Listener>::attach::ha104593d038745a6@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[1038]:0x15e0ed
<core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold::h302769bc712ef992@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[944]:0x15037a
alloc::vec::source_iter_marker::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter::h53bfefa093b74bed@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[1873]:0x1b11d8
<yew::virtual_dom::vtag::VTag as yew::virtual_dom::VDiff>::apply::hc8c58587cef4a800@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[266]:0x875c7
<yew::virtual_dom::vnode::VNode as yew::virtual_dom::VDiff>::apply::h20135d967f669cf8@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[512]:0xf863e
yew::virtual_dom::vlist::VList::apply_unkeyed::he28ed228b1b3c757@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[652]:0x11ba7e
<yew::virtual_dom::vlist::VList as yew::virtual_dom::VDiff>::apply::ha62fba5b9b02c2fa@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[205]:0x4354e
<yew::virtual_dom::vnode::VNode as yew::virtual_dom::VDiff>::apply::h20135d967f669cf8@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[512]:0xf87c1
yew::virtual_dom::vlist::VList::apply_unkeyed::he28ed228b1b3c757@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[652]:0x11ba7e
<yew::virtual_dom::vlist::VList as yew::virtual_dom::VDiff>::apply::ha62fba5b9b02c2fa@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[205]:0x4354e
<yew::virtual_dom::vtag::VTag as yew::virtual_dom::VDiff>::apply::hc8c58587cef4a800@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[266]:0x87a35
<yew::virtual_dom::vnode::VNode as yew::virtual_dom::VDiff>::apply::h20135d967f669cf8@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[512]:0xf863e
<yew::html::component::lifecycle::ComponentRunnable<COMP> as yew::scheduler::Runnable>::run::he6e158d4697eb23f@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[215]:0x50a67
std::thread::local::LocalKey<T>::with::hd525b09ea8d8ae50@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[2120]:0x1bff71
yew::scheduler::start::h18d6764a89bf3bd6@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[3425]:0x1dab8c
yew::html::component::scope::Scope<COMP>::callback::{{closure}}::h3c5b9da4ad8ee5d5@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[2304]:0x1c97f8
yew::callback::Callback<IN>::reform::{{closure}}::hf223be9f818863ed@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[292]:0x9c4c7
<yew::html::listener::events::ontransitionend::Wrapper as yew::virtual_dom::Listener>::attach::{{closure}}::hb595a3adf2aa9e89@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[2244]:0x1c6a39
<dyn core::ops::function::FnMut<(&A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hb9873ce24669ce63@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[2805]:0x1d6f11
__wbg_adapter_37@http://0.0.0.0:8080/index-96b4a740ab8d33fc.js:267:14
real@http://0.0.0.0:8080/index-96b4a740ab8d33fc.js:199:20
EventListener.handleEvent*init/imports.wbg.__wbg_addEventListener_6d9a78a5d277bdaf/<@http://0.0.0.0:8080/index-96b4a740ab8d33fc.js:551:25
handleError@http://0.0.0.0:8080/index-96b4a740ab8d33fc.js:293:18
init/imports.wbg.__wbg_addEventListener_6d9a78a5d277bdaf@http://0.0.0.0:8080/index-96b4a740ab8d33fc.js:550:79
web_sys::features::gen_EventTarget::EventTarget::add_event_listener_with_callback_and_add_event_listener_options::ha29629986626f17e@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[2729]:0x1d5a6e
<yew::html::listener::events::onclick::Wrapper as yew::virtual_dom::Listener>::attach::ha104593d038745a6@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[1038]:0x15e0ed
<core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold::h302769bc712ef992@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[944]:0x15037a
alloc::vec::source_iter_marker::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter::h53bfefa093b74bed@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[1873]:0x1b11d8
<yew::virtual_dom::vtag::VTag as yew::virtual_dom::VDiff>::apply::hc8c58587cef4a800@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[266]:0x875c7
<yew::virtual_dom::vnode::VNode as yew::virtual_dom::VDiff>::apply::h20135d967f669cf8@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[512]:0xf863e
<yew::html::component::lifecycle::ComponentRunnable<COMP> as yew::scheduler::Runnable>::run::h28badbadca79a774@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[214]:0x4f5a5
std::thread::local::LocalKey<T>::with::hd525b09ea8d8ae50@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[2120]:0x1bff71
yew::scheduler::start::h18d6764a89bf3bd6@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[3425]:0x1dab8c
yew::html::component::scope::Scope<COMP>::callback::{{closure}}::h52bb782f3e6f83d6@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[2347]:0x1cb3db
yew::callback::Callback<IN>::emit::h70345360fe2e79c8@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[2096]:0x1be8fc
homotopy_web::app::sidebar::Sidebar::install_keyboard_shortcuts::{{closure}}::h2ab08b327777a101@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[736]:0x12cd72
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h5aac0e8f46f9855f@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[2982]:0x1d8e35
__wbg_adapter_25@http://0.0.0.0:8080/index-96b4a740ab8d33fc.js:218:10
real@http://0.0.0.0:8080/index-96b4a740ab8d33fc.js:199:20
EventListener.handleEvent*init/imports.wbg.__wbg_addEventListener_936431894dca4639/<@http://0.0.0.0:8080/index-96b4a740ab8d33fc.js:548:25
handleError@http://0.0.0.0:8080/index-96b4a740ab8d33fc.js:293:18
init/imports.wbg.__wbg_addEventListener_936431894dca4639@http://0.0.0.0:8080/index-96b4a740ab8d33fc.js:547:79
web_sys::features::gen_EventTarget::EventTarget::add_event_listener_with_callback::hf266498022df7b4b@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[2742]:0x1d5e38
<homotopy_web::app::sidebar::Sidebar as yew::html::component::Component>::create::h851eb6114b3543d0@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[1266]:0x17abe1
<yew::html::component::lifecycle::ComponentRunnable<COMP> as yew::scheduler::Runnable>::run::hdce5e6ac87d2bf76@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[228]:0x614f3
std::thread::local::LocalKey<T>::with::hd525b09ea8d8ae50@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[2120]:0x1bff71
yew::scheduler::start::h18d6764a89bf3bd6@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[3425]:0x1dab8c
yew::html::component::scope::Scope<COMP>::mount_in_place::h5f7332c719f3a71a@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[912]:0x14b60b
yew::app_handle::AppHandle<COMP>::mount_with_props::h5bc2f60b3c8d0431@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[2194]:0x1c4166
yew::start_app::h6510501d7eae2125@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[2216]:0x1c5389
main_js@http://0.0.0.0:8080/index-96b4a740ab8d33fc_bg.wasm:wasm-function[2263]:0x1c7979
init@http://0.0.0.0:8080/index-96b4a740ab8d33fc.js:1028:10
async*@http://0.0.0.0:8080/:10:51


index-96b4a740ab8d33fc.js:369:21
```

**Comment by jamievicary** [comment]
Not relevant now because cubicalisation is being refactored
